component MeetupPage
js-tasks-ru/vue-20210304_aleksandra-yakovleva9 pull request #12
Opened 2021-03-25 13:41 UTC by aleksandrayakovleva132

2021-03-25 13:42 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-25 14:44 UTC, ShGKme requested changes
Требуются небольшие исправления в MeetupCover, MeetupAgenda, MeetupAgendaItem

2021-03-25 14:44 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
> +  },
Решение с `data` работает, но не реактивно. При изменении ссылки родителем значение в data не поменяется, так как оно было лишь инициализировано с входным параметром, но от него не зависит.

Здесь должно быть вычисляемое свойство.

2021-03-25 14:44 UTC, ShGKme commented on 02-components/04-MeetupInfo/MeetupInfo.js
> +        <time :datetime="dateOnlyString(date)">{{ localDate(date) }}</time>
Лучше избегать вызова методов в шаблоне. Можно использовать вычисляемое свойство.

2021-03-25 14:44 UTC, ShGKme commented on 02-components/05-MeetupAgenda/MeetupAgenda.js
> +      default: [],
Если значение по умолчанию - не примитивного типа (объект, массив), то значением свойства `default` должна быть функция, возвращающая это значение. `default: () => []`.

В противном случае получается, что у всех экземпляров этого компонента по умолчанию во входном параметре будет ссылка на один и тот же массив, случайная мутация которого приведёт к его изменению во всех экземплярах.

2021-03-25 14:44 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupView.js
> +  },
Проблема, аналогична MeetupCover.

2021-03-25 14:44 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
> +  },
Данные `data` компоненту нужны, когда у него есть некоторое внутреннее состояние, от которого оно зависит, и которое в нём меняется. Например, на странице митапов у нас хранилось состояние фильтров и полученные с API данные митапов. Эти данные изменялись, изменялось состояние компонента.

Здесь вы создали локальное состояние, в котором хранится стиль кавера. В результате компонент имеет отдельно ссылку, которая пришла от родителя, и отдельно стиль, который хранится внутри. 

Стиль - не какое-то самостоятельное состояние, не самостоятельные данные. Компонент не будет менять этот стиль в какой-то ситуации. Это нечто, что вычисляется на основе других данных.

2021-03-25 20:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-26 13:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-26 13:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-30 12:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-30 13:04 UTC, ShGKme commented on 03-sfc/03-TheToaster/components/TheToaster.vue
> +      this.$parent.$on('error', (this.addItem.message = message));
Это лишнее...
1. Родительский компонент не порождает событий.
2. Метод `$on` удалён по Vue 3
3. За очень редким исключением не нужно обращаться напрямую к родительскому компоненту через `$parent`.
4. Вторым параметром должна быть функция - обработчик события. Вы передали не функцию, а значение message, которое сразу же присваивается в сообщение нового item.

А какую задачу решает это действие?

2021-03-30 13:04 UTC, ShGKme commented on 03-sfc/03-TheToaster/components/ToasterItem.vue
> +      default: () => {},
Функция `() => {}` ничего не возвращает. Фигурные скобки здесь - это блок функции, а не объект. Если вы хотели вернуть объект, то требуется обернуть их в круглые скобки, сделав таким образом обычное выражение `() => ({ })`

2021-03-30 13:04 UTC, ShGKme commented on package.json
> +    "vue-loader": "^15.9.6",
Его можно удалить командой `npm uninstall vue-loader`

2021-03-30 13:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-31 15:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/03-TheToaster/components/TheToaster.vue
> +<script type="module">
`type="module"` здесь не нужен. Мы добавляли это, когда работали без сборщика в браузере, чтобы сообщить о том, что мы работаем с ES модулями.

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      <app-icon v-if="textButton !== null && textButton !== 'RU' && textButton !== 'EN'" :icon="iconName" />
Наличие явно вставленных в компонент проверок на какой-то один частный случай (`textButton !== 'RU' && textButton !== 'EN'`) - плохой признак. Это не компонент выбора языка, это компонент выбора варианта из списка вариантов. Тест не ожидает здесь иконку выбора языка, потому что ни в одном варианте языка нет опции `icon`.

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +    <button type="button" class="button dropdown__toggle dropdown__toggle_icon" :value="textButton">
`dropdown__toggle_icon` у элементов по условию есть только, если хотя бы у одного варианта есть иконка, а не всегда

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +        :class="{'dropdown__item_icon': item.icon}"
Аналогично, `dropdown__item_icon` у элемента по условию есть только, если **хотя бы у одного** варианта есть иконка, а не если иконка есть у непосредственно этого варианта.

Иначе при наличии иконки только у некоторых вариантов, текст не будет выравнен, иконка будет занимать место в тексте.

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +        @click="change(item, $event.target.value)"
В функцию `change` передаётся два параметра: 
1. `item`, внутри которого уже есть свойство `value`
2. `$event.target.value`, который равен `item.value` (установлен на одну строку ниже)

Это не приводит к ошибкам, но лучше избегать таких ситуаций, когда одно и тоже передаётся одновременно двумя путями. С одной стороны, возникает вопрос, а может ли второй value отличается от item.value, с другой, может появиться неожиданное поведение в будущем.

Сейчас, кстати, второй параметр в методе вообще не используется.

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      default() {
- `required: true` говорит о том, что у в параметр обязательно должно быть передано значение
- `default` используется, чтобы установить значение по умолчанию параметру, когда значение не передано (чего быть не должно при обязательности)

При этом в `default` сейчас передаётся очень странное значение. В качестве значения списка вариантов по умолчанию передаётся массив объектов в таком же формате, в котором описываются входные параметры. Но входные параметры так описываются только в опции `props` в компоненте.

Сейчас же этот код говорит, что если не передано никакое значение в `options`, но у кнопки будет три варианта:
1. У первого нет ни текста, ни значения, но есть иконка, и это объект
2. У второго есть только текст, но этот текст не строка, а объект со свойством type и объектом String в нём
3. У третьего есть только значение.

Описать ограничения на содержимое массива во входном параметре также, как описываются входные параметры - нельзя. Так можно описать только непосредственно входные параметры в опции props.

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Во Vue нельзя описать входной параметр функцией. Здесь может быть:
1. Сразу тип, например, `value: String` или `value: Array`
2. Массив типов, например, `value: [String, Array]`
3. Объект с подробным описанием параметра: его типом, 

Функция не может быть описанием входного параметра.

Более того, `options` - это массив. У массива нет свойства `value`.

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      iconName: null,
Текст кнопки, значение и иконка - это не самостоятельные данные. Это не какое-то состояние компонента, которое изменяется независимо.

Это значения, которые хранятся в некотором варианте в списке вариантов, и зависят от того, какой сейчас вариант выбран. Это должно быть вычисляемое свойство, которое на основе списка вариантов и текущего значения возвращает выбранный вариант (при наличии).

2021-03-31 15:47 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      iconName: null,
Сейчас, если родитель изменит значение компонента (какой именно вариант выбран), компонент никак не отреагирует. Проверяется нажатием на кнопку `set registration`.

2021-04-06 14:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-07 13:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-14 18:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-14 21:39 UTC, ShGKme reviewed
DropdownButton принята, в ContentTabs требуется слот

2021-04-14 21:39 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Здесь клонирование лишнее. Изменяться этот объект нигде не будет, защита в виде копии не нужна. А найти его потом при необходимости уже будет нельзя по ссылке, так как объект новый.

2021-04-14 21:39 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Так как ищется один элемент, то вместо `filter` можно использовать `find`

2021-04-14 21:39 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Это же позволит удобнее определять, есть ли выбранный вариант. Сейчас результат вычисляемого свойства - всегда объект. Либо пустой объект, либо объект с ключами 0, 1 и т.д.

Лучше вернуть `options.find()`. Тогда результатом будет либо `null`, если ничего не нашлось, либо найденный вариант.

2021-04-14 21:39 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Можно использовать метод массива [some](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some)

2021-04-14 21:39 UTC, ShGKme commented on 04-spa/01-ContentTabs/components/ContentTabs.vue
> +    <div class="content-tabs__content"><router-view :prop="tabs"/></div>
По условию компонент имеет слот для передачи содержимого. Так можно будет не только передать `<router-view>` с нужными параметрами, но и передать любой компонент или разметку, как включающую в себя `<router-view>`, так и иначе отображающую содержимое в зависимости от маршрута (например, если вместо дочерних маршрутов использовать `#hash`)

2021-04-15 09:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-15 15:39 UTC, ShGKme reviewed
Задачи приняты, но пока не все добавленные задачи решены

2021-04-15 15:39 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      }
Проверку лучше делать не на `value`, а не `optionItem`. 

`value` может иметь значение, но при этом не соответствовать никакому значению в списке вариантов. В этом случае `optionItem` будет `null`. Что логично, ведь никакой вариант не выбран. И это приведёт к ошибке в коде ниже.

2021-04-18 18:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-04-18 19:50 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-04-18 19:50 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      if (this.optionItem === undefined) {
optionItem будет `null`, если не найден. `find` возвращает `null`, если ничего не нашёл. `undefined` используют, когда значение не определено (ему не было присвоено значение), а `null` - как наличие отсутствия значения.

2021-04-18 19:50 UTC, ShGKme commented on 04-spa/01-ContentTabs/components/ContentTabs.vue
> +      <router-link v-for="link in tabs" :key="link.index" class="content-tabs__tab" active-class="content-tabs__tab_active" :to="link.to">
У `link` может не быть (и в примере задачи нет) поля `index`. Все ключи будут `undefined`

2021-04-18 19:52 UTC, merged

2021-04-19 13:57 UTC, aleksandrayakovleva132 commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      if (this.optionItem === undefined) {
у меня undefind почему-то 
![Screenshot 2021-04-19 at 16 55 18](https://user-images.githubusercontent.com/33125810/115248277-384cee00-a130-11eb-856d-dd9c4ddca26e.png)

2021-04-19 15:41 UTC, ShGKme commented on 03-sfc/04-DropdownButton-1/components/DropdownButton.vue
> +      if (this.optionItem === undefined) {
Оу, да, я вас обманул. Был уверен, что find возвращает null, если ничего не найдёт... Прошу прощения!