solution 04-04-layouts
js-tasks-ru/vue-20210304_aleksandra-yakovleva9 pull request #13
Opened 2021-04-19 14:05 UTC by aleksandrayakovleva132

2021-04-19 14:05 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-04-20 09:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-04-20 19:44 UTC, ShGKme requested changes
Вёрстка немного отличается. Это не влияет на суть задачи, но если потом собирать в проект, будет проще, если сразу сделать такую же вёрстку. Я прикрепил к комментариям ссылки на фрагменты кода, чтобы было проще.

2021-04-20 19:44 UTC, ShGKme commented on 04-spa/04-Layouts/components/FormLayout.vue
> +  </section>
Вёрстка чуть-чуть не совпадает: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/meetup-form.html#L29-L31

2021-04-20 19:44 UTC, ShGKme commented on 04-spa/04-Layouts/components/AuthLayout.vue
> +  </section>
Вёрстка чуть-чуть не совпадает:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/login.html#L30-L32

2021-04-20 19:44 UTC, ShGKme commented on 04-spa/04-Layouts/components/TheHeader.vue
> +        /></a>
Здесь также лучше сделать `router-link`

2021-04-20 19:44 UTC, ShGKme commented on 04-spa/04-Layouts/components/TheHeader.vue
> +      <router-link :to="{ name: 'login' }">Вход</router-link>
` |` можно не добавлять. В "меню" в App.vue задачи они были для ручного тестирования самой задачи :)

2021-04-27 12:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-28 18:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-05 08:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-05 14:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-10 07:44 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-14 16:05 UTC, ShGKme requested changes
Требуется поправить фиксированные заголовки в Layouts на значение заголовка из пропса, вернуть меню в TheHeader и поправить type в Buttons.

2021-06-14 16:05 UTC, ShGKme commented on 04-spa/04-Layouts/components/AuthLayout.vue
> +      <h1 class="page__title text-center">Вход</h1>
Текст заголовка может быть разным, в зависимости от входного параметра.

2021-06-14 16:05 UTC, ShGKme commented on 04-spa/04-Layouts/components/FormLayout.vue
> +      <h2 class="page__title">Редактирование митапа</h2>
Аналогично, текст заголовка может быть разным, в зависимости от входного параметра.

2021-06-14 16:05 UTC, ShGKme commented on 06-wrappers/01-Buttons/components/BaseButton.vue
> +             type="button" class="button"
В целом передавать `type="button"`, чтобы не требовалось отключать `submit` по умолчанию - удобно.

Но в такой реализации этот атрибут также будет передаваться на другие элементы, например, на ссылку `<a>`, а также будет иметь больший приоритет, чем `v-bind="$attrs"` и не позволит установить `type="submit"`

2021-06-14 16:05 UTC, ShGKme commented on 06-wrappers/01-Buttons/components/BaseButton.vue
> +  },
Что делает этот код?

2021-06-14 16:05 UTC, ShGKme commented on 04-spa/04-Layouts/components/TheHeader.vue
> +  </header>
А теперь меню совсем потерялось :(
Можно взять из материалов вебинара.
https://github.com/js-tasks-ru/vue-course-materials/blob/master/04-spa/03-vue-router/src/App.vue#L4-L24

2021-06-14 16:05 UTC, ShGKme commented on 06-wrappers/01-Buttons/components/BaseButton.vue
> +  },
В общем случае тег может быть не только строкой, но и объектом и даже функцией, также как в is у `<component>`. Можно передать имя компонента, а можно передать непосредственно сам компонент.

2021-06-14 18:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-14 18:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-14 19:01 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-06-14 19:01 UTC, ShGKme commented on 04-spa/04-Layouts/components/BaseLayout.vue
> +   <TheFooter />
Компоненты в шаблоне можно использовать и в kebab-case, и в CamelCase. Главное выбрать какой-то один силь

2021-06-14 19:02 UTC, merged