meetup radio-list
js-tasks-ru/vue-20210304_aleksandra-yakovleva9 pull request #4
Opened 2021-03-16 16:34 UTC by aleksandrayakovleva132

2021-03-16 16:35 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-17 11:58 UTC, ShGKme requested changes
Решение не соответствует условию задачи.
Цель задачи - познакомиться с обработкой событий и отслеживанием.

2021-03-17 11:58 UTC, ShGKme commented on 01-basics/03-MeetupTitle/script.js
> +const fetchMeetups = () => fetch('../api/meetups.json').then((res) => res.json());
По условию требовалось получать данные каждого митапа отдельно с `/meetups/:id` при выборе конкретного радио-переключателя. Кнопок ровно 5 от 1 до 5.

2021-03-17 11:58 UTC, ShGKme commented on 01-basics/03-MeetupTitle/script.js
> +const fetchMeetups = () => fetch('../api/meetups.json').then((res) => res.json());
Также по условию требовалось получать данные с реального API, а не соседнего JSON файла...

2021-03-17 11:58 UTC, ShGKme commented on 01-basics/03-MeetupTitle/script.js
> +  },
Это вычисляемое свойство бесполезное, так как никак не меняет данные, и возвращает просто копию массива с копией объектов

2021-03-17 20:12 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-23 21:29 UTC, closed without merging