Solution 01 04
js-tasks-ru/vue-20210304_aleksandra-yakovleva9 pull request #5
Opened 2021-03-20 11:28 UTC by aleksandrayakovleva132

2021-03-20 11:28 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-20 11:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-03-20 11:41 UTC, ShGKme requested changes
Требуется избавиться от вызова методов в шаблоне

2021-03-20 11:41 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
> +                <h5 class="meetup-agenda__title">{{ agenda.title !== null ? agenda.title : getAgenda(agenda.type, agendaTitles) }}</h5>
Здесь очень легко избавиться от вызова функций в шаблоне и использовать более декларативное решение.

2021-03-20 11:41 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +      },
Функция - это не данные приложения, не часть его состояния.
Такие функции должны быть в методах приложения.

А здесь эта функция в принципе не нужна. Можно либо сразу работать с agendaTitles и agendaIcons в шаблоне, либо применить эти данные в вычисляемом свойстве для всего митапа (всей программы) сразу.

2021-03-20 12:59 UTC, aleksandrayakovleva132 commented on 01-basics/04-MeetupPageDraft/index.html
> +                <h5 class="meetup-agenda__title">{{ agenda.title !== null ? agenda.title : getAgenda(agenda.type, agendaTitles) }}</h5>
Я не понимаю как внутри вычисляемого свойства перебирать список докладов, чтобы получать название для каждого. Например в макете я декларирую свойство `<h5 class="meetup-agenda__title">{{ meetup.agendaTitle }}</h5>`, тогда computed это все равно будет функция, которая нужна чтобы перебирать названия в цикле и отдавать конкретное заглавие для каждого
```
agendaTitle: { 
    function() {
       for (let key in agenda) {
        // ...
      }
}
}
```
получается что в шаблоне мы все равно вызываем функцию. У меня с этим каша в голове...

2021-03-21 18:58 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-21 19:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-03-22 13:28 UTC, ShGKme approved these changes
Принято 👍

2021-03-22 13:28 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/scriptTemp.js
> +              nodes: [
А что это за скрипт?...

2021-03-22 13:28 UTC, merged

2021-03-22 13:32 UTC, aleksandrayakovleva132 commented on 01-basics/04-MeetupPageDraft/scriptTemp.js
> +              nodes: [
Забыла удалить, временный файл, разбирала кейсы пока изучала материал. Удалю в другой ветке